# Generated by Django 3.0.8 on 2020-07-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeordermodel',
            name='product_status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Accepted', 'Accepted'), ('Recieved', 'Recieved'), ('Extracted', 'Extracted'), ('QCd', 'QCd'), ('Complete', 'Complete')], default='Ordered', max_length=100, null=True),
        ),
    ]
