# Generated by Django 3.0.8 on 2020-07-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200701_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeordermodel',
            name='product_category',
            field=models.CharField(choices=[('Food Nutrition', 'FoodNutrition'), ('Food Safety', 'FoodSafety'), ('Other Analysis', 'OtherAnalysis')], default='OtherAnalysis', max_length=200),
        ),
    ]
