# Generated by Django 3.0.8 on 2020-07-01 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_placeordermodel_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeordermodel',
            name='product_category',
        ),
    ]
